spring:
  application:
    name: infra-config-server
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: file://${user.home}/korprulu/workshop/config-repo/
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/